Controllers/AdminController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using NetAtlas.Data;
using NetAtlas.Models;
using System.Web;
using System.IO;
using System.Net.Mail;

namespace NetAtlas.Controllers
{
    public class AdminController : Controller
    {
        private readonly NetAtlasContext BaseDeDonnee;
        public AdminController(NetAtlasContext context)
        {
            BaseDeDonnee = context;
        }
        
        
        //Voir la liste des demandes d'inscriptions non traitées
        public async Task<IActionResult> Index()
        {
            var type = HttpContext.Session.GetString("UserType");
            if (type is not "admin")
            {
                return RedirectToAction("Login", "Membre");
            }
            else
            {
                return View(await BaseDeDonnee.Register.ToListAsync());
            }
        }

        // GET:Autoristion
        //Voir les en détails les informations du register sur un formulaire 
        public async Task<IActionResult> Autorisation(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var register = await BaseDeDonnee.Register.FindAsync(id);
            if (register == null)
            {
                return NotFound();
            }
            return View(register);
        }


        public async Task<IActionResult> Valider(int? id)
        {
            Membre menber = new Membre();
            var register = await BaseDeDonnee.Register.FindAsync(id);
            if (register == null)
            {
                return NotFound();
            }
            else
            {
                menber.Nom = register.Nom;
                menber.Prenom = register.Prenom;
                menber.Email = register.Email;
                menber.Password = register.Password;
                BaseDeDonnee.Membre.Add(menber);
                BaseDeDonnee.Remove(register);
                await BaseDeDonnee.SaveChangesAsync();

                try
                {
                    string body = "<h1>Demande d'inscription à Netatlas</h1> <p style='color:green;'> Votre demande d'inscription à NetAtlas a été approuvé.<br/>Connectez-vous";
                    EnvoiMail(menber.Email,body, "Demande d'inscription approuvée");
                    ViewBag.checkEnvoi = true;
                }
                catch (Exception ex)
                {
                    ViewBag.checkEnvoi = false;
                }
            }


            return View(menber);
        }


        // GET:Rejeter
        //Voir les en détails les informations du register sur un formulaire 
        public async Task<IActionResult> Rejeter(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var register = await BaseDeDonnee.Register.FindAsync(id);
            if (register == null)
            {
                return NotFound();
            }
            return View(register);
        }

  
        public async Task<IActionResult> Refuser(int? id)
        {
            var register = await BaseDeDonnee.Register.FindAsync(id);
            if (register == null)
            {
                return NotFound();
            }
            try
            {
                string body = "<h1>Demande d'inscription à Netatlas</h1> <p style='color:red;'> Votre demande d'inscription à NetAtlas a été rejeter.<br/>C'est la vie";
                EnvoiMail(register.Email, body, "Demande d'inscription rejetée") ;
                ViewBag.checkEnvoi = true;
            }
            catch (Exception)
            {
                ViewBag.checkEnvoi = false;
            }
           
           BaseDeDonnee.Remove(register);
           await BaseDeDonnee.SaveChangesAsync();
           return View(register);
        }



        public void EnvoiMail(string adr,string body,string subject)
        {
            

             MailMessage mail = new MailMessage();
            
            mail.Priority = MailPriority.High;
            mail.IsBodyHtml = true;
            mail.Body = body;
            mail.Subject = subject; 
            mail.From = new MailAddress("netatlas2022@gmail.com");
            mail.To.Add(new MailAddress(adr));

            SmtpClient client = new SmtpClient("smtp.gmail.com",587);
            client.EnableSsl = true;
            client.Credentials = new System.Net.NetworkCredential("netatlas2022@gmail.com", "Qsdf#2022");
            client.Send(mail);

        }


         public async Task<IActionResult> MembresAverti()
         {
            return View(await BaseDeDonnee.Membre.Where(m=>m.NbrAvertissement>=3).ToListAsync());
         }
        public async Task<IActionResult> SuppMembre(int id)
        {
            var menber = await BaseDeDonnee.Membre.FindAsync(id);
            if (menber is null)
            {
                return NotFound();
            }
            return View(menber);
        }

        

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ValiderSup(int id)
        {
            var menber = await BaseDeDonnee.Membre.FindAsync(id);
            try
            {
                string body = "<h1>Suppression du compte</h1> <p style='color:red;'>En raison de vos violations multiples des politiques de NetAtlas vous avez été banni<br/>";
                EnvoiMail(menber.Email, body, "Bannissement de NetAtlas");
                ViewBag.checkEnvoi = true;
            }
            catch (Exception ex)
            {
                ViewBag.checkEnvoi = false;
            }
            BaseDeDonnee.Remove(menber);
            await BaseDeDonnee.SaveChangesAsync();
            return View();
        }


        public async Task<IActionResult> RestaureMembre(int id)
        {
            var menber = await BaseDeDonnee.Membre.FindAsync(id);
            if (menber is null)
            {
                return NotFound();
            }
            return View(menber);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ValiderRes(int id)
        {
            var menber = await BaseDeDonnee.Membre.FindAsync(id);
            try
            {
                string body = "<h1>Restauration du compte</h1> <p style='color:green;'>Les compteurs sont remis à zéro<br/>";
                EnvoiMail(menber.Email, body, "Bannissement de NetAtlas");
                ViewBag.checkEnvoi = true;
            }
            catch (Exception)
            {
                ViewBag.checkEnvoi = false;
            }
            menber.NbrAvertissement = 0;
            BaseDeDonnee.Update(menber);
            await BaseDeDonnee.SaveChangesAsync();
            return View(menber);
        }


        public async Task<IActionResult> Liste()
        {
            return View(await BaseDeDonnee.Membre.ToListAsync());
        }

        public async Task<IActionResult> SupPub()
        {
            

                var q1 = await BaseDeDonnee.Publication.ToListAsync();
                var mylist = new List<Dictionary<string, object>>();

                foreach (var item in q1)
                {
                    if (item.etat == true)
                    {
                        var dico = new Dictionary<string, object>();
                        var res = await BaseDeDonnee.Lien.AnyAsync(r => r.IdPublication == item.Id);
                        var res2 = await BaseDeDonnee.Message.AnyAsync(r => r.IdPublication == item.Id);
                        var res3 = await BaseDeDonnee.PhotoVideo.AnyAsync(r => r.IdPublication == item.Id);
                        if (res is true)
                        {
                            dico.Add("publication", item);

                            dico.Add("ressource", await BaseDeDonnee.Lien.FirstAsync(r => r.IdPublication == item.Id));
                        }
                        else if (res2 is true)
                        {
                            dico.Add("publication", item);

                            dico.Add("ressource", await BaseDeDonnee.Message.FirstAsync(r => r.IdPublication == item.Id));
                        }
                        else if (res3 is true)
                        {
                            dico.Add("publication", item);

                            dico.Add("ressource", await BaseDeDonnee.PhotoVideo.FirstAsync(r => r.IdPublication == item.Id));
                        }

                        if (res == true || res2 == true || res3 == true)
                            mylist.Add(dico);
                    }
                }
                ViewBag.check = false;
                ViewBag.ListPub = mylist;
                return View();
             
           
        }


        [HttpPost, ActionName("SupPub")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (id == null)
                return NotFound();
            var pu = await BaseDeDonnee.Publication.FindAsync(id);
            ViewBag.check = true;
            if (pu == null)
                return NotFound();
            BaseDeDonnee.Publication.Remove(pu);
            await BaseDeDonnee.SaveChangesAsync();


            var q1 = await BaseDeDonnee.Publication.ToListAsync();
            var mylist = new List<Dictionary<string, object>>();

            foreach (var item in q1)
            {
                if (item.etat == true)
                {
                    var dico = new Dictionary<string, object>();
                    var res = await BaseDeDonnee.Lien.AnyAsync(r => r.IdPublication == item.Id);
                    var res2 = await BaseDeDonnee.Message.AnyAsync(r => r.IdPublication == item.Id);
                    var res3 = await BaseDeDonnee.PhotoVideo.AnyAsync(r => r.IdPublication == item.Id);
                    if (res is true)
                    {

Controllers/LiensController.cs
#nullable disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.Json;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using NetAtlas.Data;
using NetAtlas.Models;

namespace NetAtlas.Controllers
{
    public class LiensController : Controller
    {
        private readonly NetAtlasContext _context;

        public LiensController(NetAtlasContext context)
        {
            _context = context;
        }

        public Membre? GetMembre()
        {
            var value = HttpContext.Session.GetString("UserSession");
            return value == null ? null : JsonSerializer.Deserialize<Membre>(value);
        }

        // GET: Liens
        public async Task<IActionResult> Index()
        {
            var netAtlasContext = _context.Lien.Include(l => l.Publication);
            return View(await netAtlasContext.ToListAsync());
        }

        // GET: Liens/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var lien = await _context.Lien
                .Include(l => l.Publication)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (lien == null)
            {
                return NotFound();
            }

            return View(lien);
        }

        // GET: Liens/Create
        public IActionResult Create()
        {
            var type = HttpContext.Session.GetString("UserType");
            if (type is not "membre")
            {
                return Unauthorized();
            }
            var user = GetMembre();
            ViewBag.Membre = user.Nom + " " + user.Prenom;
            return View();
        }

        // POST: Liens/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create( string Url, string nomRessource)
        {
            var type = HttpContext.Session.GetString("UserType");
            if (type is not "membre")
            {
                return Unauthorized();
            }
            var user = GetMembre();
            Publication p = new Publication();
            p.DatePublication = DateTime.Now;
            p.IdMemdre = user.Id;
            _context.Publication.Add(p);
            await _context.SaveChangesAsync();
            var Lien = new Lien();
            Lien.IdPublication = p.Id;
            Lien.Url = Url;
            Lien.nomRessource = nomRessource;
            ViewBag.Membre = user.Nom + " " + user.Prenom;
            _context.Lien.Add(Lien);
            await _context.SaveChangesAsync();
            return RedirectToAction("MesPub","Membre");
           
        }

        // GET: Liens/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var lien = await _context.Lien.FindAsync(id);
            if (lien == null)
            {
                return NotFound();
            }
            return View(lien);
        }

        // POST: Liens/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Url,Id,IdPublication,nomRessource")] Lien lien)
        {
            if (id != lien.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(lien);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!LienExists(lien.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["IdPublication"] = new SelectList(_context.Publication, "Id", "Id", lien.IdPublication);
            return View(lien);
        }

        // GET: Liens/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var lien = await _context.Lien
                .Include(l => l.Publication)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (lien == null)
            {
                return NotFound();
            }

            return View(lien);
        }

        // POST: Liens/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var lien = await _context.Lien.FindAsync(id);
            _context.Lien.Remove(lien);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool LienExists(int id)
        {
            return _context.Lien.Any(e => e.Id == id);
        }
    }
}

Views/Shared/_LayoutAdmin.cshtml
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - NetAtlas</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/NetAtlas.styles.css" asp-append-version="true" />
    <!-- Favicons -->
    <link href="~/assets/img/favicon.png" rel="icon">
    <link href="~/assets/img/apple-touch-icon.png" rel="apple-touch-icon">

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Roboto:300,300i,400,400i,500,500i,700,700i&display=swap" rel="stylesheet">

    <!-- Vendor CSS Files -->
    <link href="~/assets/vendor/animate.css/animate.min.css" rel="stylesheet">
    <link href="~/assets/vendor/aos/aos.css" rel="stylesheet">
    <link href="~/assets/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="~/assets/vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet">
    <link href="~/assets/vendor/boxicons/css/boxicons.min.css" rel="stylesheet">
    <link href="~/assets/vendor/glightbox/css/glightbox.min.css" rel="stylesheet">
    <link href="~/assets/vendor/swiper/swiper-bundle.min.css" rel="stylesheet">

    <!-- Template Main CSS File -->
    <link href="~/assets/css/style.css" rel="stylesheet">
</head>
<body>
    <header id="header" class="fixed-top d-flex align-items-center ">
    <div class="container d-flex justify-content-between align-items-center">

      <div class="logo">
        <h1 class="text-light"><a asp-action="Index" asp-controller="Home"><span>NETATLAS</span></a></h1>
        <!-- Uncomment below if you prefer to use an image logo -->
        <!-- <a href="index.html"><img src="assets/img/logo.png" alt="" class="img-fluid"></a>-->
      </div>

      <nav id="navbar" class="navbar">
        <ul>
          @*<li><a class="active"  >Acceuil</a></li>
          <li><a href="about.html">About</a></li>*@
          <li class="text-warning"><a>Bonjour Admin</a></li>
          <li><a asp-controller="Admin" asp-action="SupPub">Publications avertis</a></li>
          <li><a asp-controller="Admin" asp-action="MembresAverti">Membres à supprimer</a></li>
          <li><a asp-controller="Admin" asp-action="Liste">Liste des membres</a></li>
          <li><a asp-controller="Admin" asp-action="Index">Inscriptions en attente</a></li>

          <li><a class="text-danger" asp-controller="Membre" asp-action="Deconnexion">Se deconnecter</a></li>
        </ul>
        <i class="bi bi-list mobile-nav-toggle"></i>
      </nav><!-- .navbar -->

    </div>
  </header><!-- End Header -->
    <div class="container page">
        <main role="main" id="main" class="pb-3">
            <div class="mt-5">
            @RenderBody()
            </div>
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - NetAtlas - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <style>
   /**     
*
{
    font-family: Arial, Helvetica,sans-serif;
    margin: 0px;
    padding: 0px;
    box-sizing: border-box;
}

.page
{
    background:;
    height:100vh;
}



      :root
{
    --main-color:blue;
}
.theme-color
{
    color:var(--main-color);
}

button.btn
{
    
    background: none;
    border: 2px solid var(--main-color);
    border-radius: 10px;
}
button.btn:hover
{
    background-color: var(--main-color);
}
button a{
    text-decoration: none;
    color: var(--main-color);
}
button a:hover
{
    font-size:16px;
}

.navbar ul li a
{
    padding: 5px 15px;
    margin: 0px 5px;
}
.navbar ul li a.act, .navbar ul li a:hover
{
    background: var(--main-color);
    color: white !important;
   
}*/
    </style>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    <!-- Vendor JS Files -->
  <script src="~/assets/vendor/purecounter/purecounter.js"></script>
  <script src="~/assets/vendor/aos/aos.js"></script>
  <script src="~/assets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
  <script src="~/assets/vendor/glightbox/js/glightbox.min.js"></script>
  <script src="~/assets/vendor/isotope-layout/isotope.pkgd.min.js"></script>
  <script src="~/assets/vendor/swiper/swiper-bundle.min.js"></script>
  <script src="~/assets/vendor/waypoints/noframework.waypoints.js"></script>
  <script src="~/assets/vendor/php-email-form/validate.js"></script>

  <!-- Template Main JS File -->
  <script src="~/assets/js/main.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_LayoutMembre.cshtml
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - NetAtlas</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/NetAtlas.styles.css" asp-append-version="true" />
    <!-- Favicons -->
    <link href="~/assets/img/favicon.png" rel="icon">
    <link href="~/assets/img/apple-touch-icon.png" rel="apple-touch-icon">

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Roboto:300,300i,400,400i,500,500i,700,700i&display=swap" rel="stylesheet">

    <!-- Vendor CSS Files -->
    <link href="~/assets/vendor/animate.css/animate.min.css" rel="stylesheet">
    <link href="~/assets/vendor/aos/aos.css" rel="stylesheet">
    <link href="~/assets/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="~/assets/vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet">
    <link href="~/assets/vendor/boxicons/css/boxicons.min.css" rel="stylesheet">
    <link href="~/assets/vendor/glightbox/css/glightbox.min.css" rel="stylesheet">
    <link href="~/assets/vendor/swiper/swiper-bundle.min.css" rel="stylesheet">

    <!-- Template Main CSS File -->
    <link href="~/assets/css/style.css" rel="stylesheet">
</head>
<body>
    <header id="header" class="fixed-top d-flex align-items-center ">
    <div class="container d-flex justify-content-between align-items-center">

      <div class="logo">
        <h1 class="text-light"><a href="index.html"><span>NetAtlas</span></a></h1>
        <!-- Uncomment below if you prefer to use an image logo -->
        <!-- <a href="index.html"><img src="assets/img/logo.png" alt="" class="img-fluid"></a>-->
      </div>

      <nav id="navbar" class="navbar">
        <ul>
          @*<li><a class="active"  >Acceuil</a></li>
          <li><a href="about.html">About</a></li>*@
          <li class="text-warning"><a>Bonjour @ViewBag.Membre</a></li>
          <li><a asp-controller="Membre" asp-action="RetirerAmi">Voir mes amis</a></li>
          <li class="dropdown"><a href="#"><span>Publications</span> <i class="bi bi-chevron-down"></i></a>
            <ul>
              <li><a asp-action="MesPub" asp-controller="Membre">Voir mes publications</a></li>
              <li class="dropdown"><a href="#"><span>Faire une publication</span> <i class="bi bi-chevron-right"></i></a>
                <ul>
                  @*<li><a href="#">Deep Drop Down 1</a></li>
                  <li><a href="#">Deep Drop Down 2</a></li>*@
                  <li><a asp-controller="Liens" asp-action="Create">Publier un lien</a></li>
                  <li><a asp-controller="Messages" asp-action="Create">Publier un message</a></li>
                  <li><a asp-controller="PhotoVideos" asp-action="Create">Publier un media</a></li>
                </ul>
              </li>
              <li><a asp-controller="Publication" asp-action="Index">publications de mes amis</a></li>
            </ul>
          </li>
           <li class="dropdown"><a href="#"><span>Invitations</span> <i class="bi bi-chevron-down"></i></a>
            <ul>
              <li><a asp-controller="Membre" asp-action="ListeMembre">Envoyer une invitation</a></li>
              <li><a asp-controller="Amities" asp-action="Index">Voir les invitations reçus</a></li>
              @*<li><a href="#">Voir les invitations reçus</a></li>
              <li><a href="#">Drop Down 4</a></li>*@
            </ul>
          </li>
          <li><a asp-controller="Membre" asp-action="Deconnexion">Se deconnecter</a></li>
        </ul>
        <i class="bi bi-list mobile-nav-toggle"></i>
      </nav><!-- .navbar -->

    </div>
  </header><!-- End Header -->
    <div class="container page mt-5">
        <main role="main" id="main" class="pb-3">
            <div class="mt-5">
            @RenderBody()
            </div>
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - NetAtlas - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <style>
   /**     
*
{
    font-family: Arial, Helvetica,sans-serif;
    margin: 0px;
    padding: 0px;
    box-sizing: border-box;
}

.page
{
    background:;
    height:100vh;
}



      :root
{
    --main-color:blue;
}
.theme-color
{
    color:var(--main-color);
}

button.btn
{
    
    background: none;
    border: 2px solid var(--main-color);
    border-radius: 10px;
}
button.btn:hover
{
    background-color: var(--main-color);
}
button a{
    text-decoration: none;
    color: var(--main-color);
}
button a:hover
{
    font-size:16px;
}

.navbar ul li a
{
    padding: 5px 15px;
    margin: 0px 5px;
}
.navbar ul li a.act, .navbar ul li a:hover
{
    background: var(--main-color);
    color: white !important;
   
}*/
    </style>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    <!-- Vendor JS Files -->
  <script src="~/assets/vendor/purecounter/purecounter.js"></script>
  <script src="~/assets/vendor/aos/aos.js"></script>
  <script src="~/assets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
  <script src="~/assets/vendor/glightbox/js/glightbox.min.js"></script>
  <script src="~/assets/vendor/isotope-layout/isotope.pkgd.min.js"></script>
  <script src="~/assets/vendor/swiper/swiper-bundle.min.js"></script>
  <script src="~/assets/vendor/waypoints/noframework.waypoints.js"></script>
  <script src="~/assets/vendor/php-email-form/validate.js"></script>

  <!-- Template Main JS File -->
  <script src="~/assets/js/main.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>