Models/Moderateur.cs
using System.ComponentModel.DataAnnotations;

namespace NetAtlas.Models
{
    public class Moderateur
    {
        [Key]
        public int Id { get; set; }

        [Required]
        [Display(Name = "Mot de passe du modérateur"),DataType(DataType.Password)]
        public string Password { get; set; }

        public string Nom { get; set; }
        public string Prenom { get; set; }

        [Required]
        public string Email { get; set; }
        public int isLogged { get; set; } = 0;
    }
}

Controllers/ModerateursController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Mail;
using System.Text.Json;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using NetAtlas.Data;
using NetAtlas.Models;
namespace NetAtlas.Controllers
{
    public class ModerateursController : Controller
    {
        private readonly NetAtlasContext _context;

        public ModerateursController(NetAtlasContext context)
        {
            _context = context;
        }

        public Moderateur? GetModerateur()
        {
            var value = HttpContext.Session.GetString("UserSession");
            return value == null ? null : JsonSerializer.Deserialize<Moderateur>(value);
        }

        // GET: Moderateurs
        public async Task<IActionResult> Index()
        {
            var type = HttpContext.Session.GetString("UserType");
            if (type is not "moderateur")
            {
                return RedirectToAction("Login", "Membre");
            }
            else
            {
                var user = GetModerateur();
                ViewBag.Moderateur = user.Nom + " " + user.Prenom;
                var q1 = await _context.Publication.ToListAsync();
                var mylist = new List<Dictionary<string, object>>();

                foreach (var item in q1)
                {
                    if (item.etat == false)
                    {
                        var dico = new Dictionary<string, object>();
                        var res = await _context.Lien.AnyAsync(r => r.IdPublication == item.Id);
                        var res2 = await _context.Message.AnyAsync(r => r.IdPublication == item.Id);
                        var res3 = await _context.PhotoVideo.AnyAsync(r => r.IdPublication == item.Id);
                        if (res is true)
                        {
                            dico.Add("publication", item);

                            dico.Add("ressource", await _context.Lien.FirstAsync(r => r.IdPublication == item.Id));
                        }
                        else if (res2 is true)
                        {
                            dico.Add("publication", item);

                            dico.Add("ressource", await _context.Message.FirstAsync(r => r.IdPublication == item.Id));
                        }
                        else if (res3 is true)
                        {
                            dico.Add("publication", item);

                            dico.Add("ressource", await _context.PhotoVideo.FirstAsync(r => r.IdPublication == item.Id));
                        }

                        if (res == true || res2 == true || res3 == true)
                            mylist.Add(dico);
                    }
                }
                
                ViewBag.ListPub = mylist;
                return View();
            }
        }
        // GET: Moderateurs/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var moderateur = await _context.Moderateur
                .FirstOrDefaultAsync(m => m.Id == id);
            if (moderateur == null)
            {
                return NotFound();
            }

            return View(moderateur);
        }

        // GET: Moderateurs/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Moderateurs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Password,Nom,Prenom,Email,isLogged")] Moderateur moderateur)
        {
            if (ModelState.IsValid)
            {
                _context.Add(moderateur);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(moderateur);
        }

        // GET: Moderateurs/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var moderateur = await _context.Moderateur.FindAsync(id);
            if (moderateur == null)
            {
                return NotFound();
            }
            return View(moderateur);
        }

        // POST: Moderateurs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Password,Nom,Prenom,Email,isLogged")] Moderateur moderateur)
        {
            if (id != moderateur.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(moderateur);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ModerateurExists(moderateur.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(moderateur);
        }

        // GET: Moderateurs/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var moderateur = await _context.Moderateur
                .FirstOrDefaultAsync(m => m.Id == id);
            if (moderateur == null)
            {
                return NotFound();
            }

            return View(moderateur);
        }

        // POST: Moderateurs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var moderateur = await _context.Moderateur.FindAsync(id);
            _context.Moderateur.Remove(moderateur);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ModerateurExists(int id)
        {
            return _context.Moderateur.Any(e => e.Id == id);
        }

        public async Task<IActionResult> Avertir(int ? id)
        {
            if(id is null)
            {
                return NotFound();
            }
                
            var res = _context.Ressource.Include(r => r.Publication).FirstOrDefault(m => m.Id == id);
            if (res.Publication == null)
            {
                return NotFound(res.Publication);
            }
                

            var menber = await _context.Membre.FirstOrDefaultAsync(m => m.Id==res.Publication.IdMemdre);  
            if(menber ==null)
            {
                return NotFound(menber);
            }
            menber.NbrAvertissement += 1;
            res.Publication.etat = true;
            try
            {
                string body = "<h1>Avertissement d'une publication</h1> <p style='color:red;'>Une de vos publication ne respectant pas les politiques de NetAtlas a été supprimée<br/>Sachez qu'après 3 avertissement vous pourriez etre banni de notre communauté";
                EnvoiMail(menber.Email, body, "Avertissement");
                ViewBag.checkEnvoi = true;
            }
            catch (Exception)
            {
                ViewBag.checkEnvoi = false;
            }
            
            _context.Update(res.Publication);
            _context.Update(menber);
            await _context.SaveChangesAsync();
            return View();
        }


        public void EnvoiMail(string adr, string body, string subject)
        {


            MailMessage mail = new MailMessage();

            mail.Priority = MailPriority.High;
            mail.IsBodyHtml = true;
            mail.Body = body;
            mail.Subject = subject;
            mail.From = new MailAddress("netatlas2022@gmail.com");
            mail.To.Add(new MailAddress(adr));

            SmtpClient client = new SmtpClient("smtp.gmail.com", 587);
            client.EnableSsl = true;
            client.Credentials = new System.Net.NetworkCredential("netatlas2022@gmail.com", "Qsdf#2022");
            client.Send(mail);

        }

        public async Task<IActionResult> Liste()
        {
            return View(await _context.Membre.ToListAsync());
        }

    }
}

Views/Moderateurs/Avertir.cshtml
@model NetAtlas.Models.Moderateur

@{
    ViewData["Title"] = "Avertir";
}


<html>
        <body onload="redirection()">
        @if (ViewBag.checkEnvoi){
            <div class="alert alert-success alert-dismissible col-3 rounded" role="alert" style="margin-right:0px;margin-top:0px">
              <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span></button>
              L' email a bien été envoyé
            </div>
        }
        else
        {
            <div class="alert alert-warning alert-dismissible col-3" role="alert" style="margin-right:0px;margin-top:0px">
              <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span></button>
              L' email n' a pas pu être envoyé
            </div>
        }

        <h1 class="text-success">Cette publication a bien été avertie</h1>
        

        <script>
            function f()
            {
                window.location.replace("../Index");
            }

            function redirection()
            {
                setTimeout(f,5000);
            }

    
        </script>
    </body>
</html>

Views/Moderateurs/Create.cshtml
@model NetAtlas.Models.Moderateur

@{
    ViewData["Title"] = "Create";
    Layout = "_LayoutAdmin";
}

<h1>Create</h1>

<h4>Moderateur</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Password" class="control-label"></label>
                <input asp-for="Password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Nom" class="control-label"></label>
                <input asp-for="Nom" class="form-control" />
                <span asp-validation-for="Nom" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Prenom" class="control-label"></label>
                <input asp-for="Prenom" class="form-control" />
                <span asp-validation-for="Prenom" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Moderateurs/Details.cshtml
@model NetAtlas.Models.Moderateur

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Moderateur</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Password)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Password)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nom)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nom)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Prenom)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Prenom)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.isLogged)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.isLogged)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/Moderateurs/Edit.cshtml
@model NetAtlas.Models.Moderateur

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Moderateur</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Password" class="control-label"></label>
                <input asp-for="Password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Nom" class="control-label"></label>
                <input asp-for="Nom" class="form-control" />
                <span asp-validation-for="Nom" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Prenom" class="control-label"></label>
                <input asp-for="Prenom" class="form-control" />
                <span asp-validation-for="Prenom" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="isLogged" class="control-label"></label>
                <input asp-for="isLogged" class="form-control" />
                <span asp-validation-for="isLogged" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Moderateurs/Index.cshtml
@model IEnumerable<NetAtlas.Models.Publication>

@{
    Layout = "_LayoutModerateur";
}

<div class = "container">
    @if(ViewBag.ListPub!=null)
    {
      
   
        @foreach (var item in ViewBag.ListPub)
        {
            if(item["ressource"] is Lien)
            {
                <div class="container col-6 bg-light justify-content-center rounded-2 p-3">
                    <small>lien posté le @item["publication"].DatePublication</small>
                    <h3 class="text-center text-primary">@item["ressource"].nomRessource</h3>
                    <a href='@item["ressource"]'>@item["ressource"].Url</a>
                    <p>
                        <a asp-controller="Moderateurs" asp-action="Avertir" asp-route-id='@item["ressource"].Id'>
                        <input type="button" class="btn btn-primary" value="Avertir"/>
                    </a> 
                    </p>
                </div><br />
                
            }
            if(item["ressource"] is Message)
            {
                <div class="container col-6 bg-light justify-content-center rounded-2 p-3">
                    <small>Message posté le @item["publication"].DatePublication</small>
                    <h3 class="text-center text-primary">@item["ressource"].nomRessource</h3>
                    <p>@item["ressource"].contenu</p>
                    <p>
                    <a asp-controller="Moderateurs" asp-action="Avertir" asp-route-id='@item["ressource"].Id'>
                        <input type="button" class="btn btn-primary" value="Avertir"/>
                    </a> 
                </p> 
                </div><br />
                
            }

            if(item["ressource"] is PhotoVideo && item["ressource"].TypeMedia==1)
            {
                <div class="container col-6 bg-light justify-content-center rounded-2 p-3">
                    <small>Image posté le @item["publication"].DatePublication</small>
                    <h3 class="text-center text-primary">@item["ressource"].nomRessource</h3>
                    <img class="rounded mx-auto d-block" src=@item["ressource"].Chemin alt='yfyu'/><br>
                    <p>
                        <a asp-controller="Moderateurs" asp-action="Avertir" asp-route-id='@item["ressource"].Id'>
                            <input type="button" class="btn btn-primary" value="Avertir"/>
                        </a> 
                    </p>
                </div><br />
            }
            else if(item["ressource"] is PhotoVideo && item["ressource"].TypeMedia==2)
            {
                <div class="container col-6 bg-light justify-content-center rounded-2 p-3">
                    <small>vidéo posté le @item["publication"].DatePublication</small>
                    <h3 class="text-center text-primary">@item["ressource"].nomRessource</h3><br>
          
                    <iframe class="rounded mx-auto d-block" src='@item["ressource"].Chemin'> </iframe>

                    @*<video width="320" height="240" controls>
                      <source src='@item["ressource"].Chemin' type=video/mp4>
                    </video>*@
                    <p>
                        <a asp-controller="Moderateurs" asp-action="Avertir" asp-route-id='@item["ressource"].Id'>
                            <input type="button" class="btn btn-primary" value="Avertir"/>
                        </a> 
                    </p>
                </div><br />
            }
        }
    }
    else
    {
        <h3>Aucune publication présente</h3>
    }
</div>

Views/Moderateurs/ListMembre.cshtml
@model IEnumerable<NetAtlas.Models.Membre>

@{
    ViewData["Title"] = "Liste des Membre";
    Layout = "~/Views/Shared/_LayoutModerateur.cshtml";
}

<h1>Liste des Membre</h1>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nom)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Prenom)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
           
            <th>
                @Html.DisplayNameFor(model => model.NbrAvertissement)
            </th>
           
            <!--<th></th>-->
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Nom)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Prenom)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Password)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NbrAvertissement)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.isLogged)
            </td>
            <!--<td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>-->
        </tr>
}
    </tbody>
</table>

Views/Moderateurs/Liste.cshtml
@model IEnumerable<NetAtlas.Models.Membre>

@{
    ViewData["Title"] = "Liste de tous les membre";
    Layout = "_LayoutModerateur";
}

<h1>Liste de tous les membre</h1>


<table class="table table-striped">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nom)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Prenom)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            
            <th>
                @Html.DisplayNameFor(model => model.NbrAvertissement)
            </th>
            
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Nom)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Prenom)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
           
            <td>
                @Html.DisplayFor(modelItem => item.NbrAvertissement)
            </td>
           
        </tr>
}
    </tbody>
</table>