Models/Membre.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Diagnostics.CodeAnalysis;

namespace NetAtlas.Models
{
    public class Membre
    {
        [Key]
        public int Id { get; set; }

        [StringLength(50)]
        public string Nom { get; set; }

        [StringLength(100)]
        public string Prenom { get; set; }

        [Required,DataType(DataType.EmailAddress)]
        [Display(Name = "Adresse mail")]
        [StringLength(100)]
        public string Email { get; set; }

        [Display(Name = "Mot de passe utilisateur")]
        [MinLength(8, ErrorMessage = "Le mot de passe est trop court "),DataType(DataType.Password)]
        [Required]
        public string Password { get; set; }

        public int NbrAvertissement { get; set; } = 0;

        [ScaffoldColumn(false)]
        public string? PhotoProfil { get; set; }
        public int isLogged { get; set; } = 0;


        public Membre()
        {

        }
    }
}

Controllers/AmitiesController.cs
#nullable disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.Json;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using NetAtlas.Data;
using NetAtlas.Models;

namespace NetAtlas.Controllers
{
    public class AmitiesController : Controller
    {
        private readonly NetAtlasContext _context;

        public AmitiesController(NetAtlasContext context)
        {
            _context = context;
        }
        public Membre? GetMembre()
        {
            var value = HttpContext.Session.GetString("UserSession");
            return value == null ? null : JsonSerializer.Deserialize<Membre>(value);
        }

        // GET: Amities
        public async Task<IActionResult> Index()
        {
            var type = HttpContext.Session.GetString("UserType");
            if (type is not "membre")
            {
                return Unauthorized();
            }
            var user = GetMembre();
            ViewBag.Membre = user.Nom + " " + user.Prenom;
            var netAtlasContext = _context.Amitie.Include(a => a.Sender).Where(a=>a.IdReceiver==user.Id && a.Statut==0);
            return View(await netAtlasContext.ToListAsync());
        }

        // GET: Amities/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var amitie = await _context.Amitie
                .Include(a => a.Receiver)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (amitie == null)
            {
                return NotFound();
            }

            return View(amitie);
        }

        

        // POST: Amities/Create/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(int? id)
        {
            var receiver = await _context.Membre.FindAsync(id);
            var type = HttpContext.Session.GetString("UserType");
            if (type is not "membre")
            {
                return RedirectToAction("Login","Membre");
            }
            else
            {
                var user = GetMembre();
                var amitie = new Amitie();
                amitie.IdSender = user.Id;
                amitie.Receiver = receiver;
                amitie.IdReceiver = receiver.Id;
                amitie.Statut = 0;
                try
                {
                    _context.Add(amitie);
                    await _context.SaveChangesAsync();
                }
                catch
                {
                    throw;
                }

                return RedirectToAction("ListeMembre", "Membre");
            }
        }

        // POST: Amities/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id)
        {
            var amitie = _context.Amitie.Find(id);

            if (amitie is Amitie)
            {
                amitie.Statut=1;
                try
                {
                    _context.Update(amitie);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AmitieExists(amitie.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return RedirectToAction(nameof(Index));
        }

        // GET: Amities/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var amitie = await _context.Amitie
                .Include(a => a.Receiver)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (amitie == null)
            {
                return NotFound();
            }

            return View(amitie);
        }

        // POST: Amities/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var amitie = await _context.Amitie.FindAsync(id);
            _context.Amitie.Remove(amitie);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool AmitieExists(int id)
        {
            return _context.Amitie.Any(e => e.Id == id);
        }
    }
}

Controllers/MembreController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using NetAtlas.Data;
using NetAtlas.Models;
using Microsoft.AspNetCore.Http;
using System.Text.Json;

namespace NetAtlas.Controllers
{
    public class MembreController : Controller
    {
        private readonly NetAtlasContext bd;
        public MembreController(NetAtlasContext context)
        {
            bd = context;
        }
        public Membre? GetMembre()
        {
            var value = HttpContext.Session.GetString("UserSession");
            return value == null ? null : JsonSerializer.Deserialize<Membre>(value);
        }
        private bool MemberExists(int id)
        {
            return bd.Membre.Any(e => e.Id == id);
        }
        private bool AdminExists(int id)
        {
            return bd.Admin.Any(a => a.Id == id);
        }
        private bool ModerateurExists(int id)
        {
            return bd.Moderateur.Any(m => m.Id == id);
        }
        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Login(string? password, string? email)
        {
            var member = await bd.Membre.FirstOrDefaultAsync(m => m.Email == email);
            var admin = await bd.Admin.FirstOrDefaultAsync(ad => ad.Email == email);
            var moderateur = await bd.Moderateur
                .FirstOrDefaultAsync(mo => mo.Email == email);

            if (member != null)
            {
                if (member.Password == password)
                {
                    member.isLogged = 1;
                    try
                    {

                        bd.Update(member);
                        await bd.SaveChangesAsync();
                        HttpContext.Session.SetString("UserSession", JsonSerializer.Serialize(member));
                        HttpContext.Session.SetString("UserType", "membre");
                        return RedirectToAction("Index", "Publication");

                    }
                    catch (DbUpdateConcurrencyException)
                    {
                        if (!MemberExists(member.Id))
                        {
                            return NotFound();
                        }
                        else
                        {
                            throw;
                        }
                    }

                }
            }
            else
            {
                if (admin != null)
                {
                    if (admin.Password == password)
                    {
                        admin.isLogged = 1;
                        try
                        {
                            bd.Update(admin);
                            await bd.SaveChangesAsync();
                            HttpContext.Session.SetString("UserSession", JsonSerializer.Serialize(admin));
                            HttpContext.Session.SetString("UserType", "admin");
                            return RedirectToAction("Index", "Admin");
                        }
                        catch
                        {
                            if (!AdminExists(admin.Id))
                            {
                                return NotFound();
                            }
                            else { throw; }
                        }
                    }
                }
                else
                {
                    if (moderateur != null)
                    {
                        if (moderateur.Password == password)
                        {
                            moderateur.isLogged = 1;
                            try
                            {
                                bd.Update(moderateur);
                                await bd.SaveChangesAsync();
                                HttpContext.Session.SetString("UserSession", JsonSerializer.Serialize(moderateur));
                                HttpContext.Session.SetString("UserType", "moderateur");
                                return RedirectToAction("Index", "Moderateurs");

                            }
                            catch
                            {
                                if (!ModerateurExists(moderateur.Id)) { return NotFound(); }
                                else { throw; }
                            }
                        }
                    }
                    else
                    {
                        ViewBag.NoneValid = "Email ou mot de passe incorrect";

                    }
                }

            }
            ViewBag.NoneValid = "Email ou mot de passe incorrect";

            return View();
        }

        public ActionResult Deconnexion()
        {
            HttpContext.Session.Remove("userSession");
            HttpContext.Session.Remove("UserType");
            return RedirectToAction("Index", "Home");
            
        }
        public async Task<IActionResult> ListeMembre()
        {
            var type = HttpContext.Session.GetString("UserType");
            if (type is not "membre")
            {
                return RedirectToAction("Login", "Membre");
            }
            else
            {
                var user = GetMembre();

                ViewBag.Membre = user.Nom + " " + user.Prenom;

                var q = await bd.Membre.Where(m => m.Id != user.Id).ToListAsync();
                var q2 = bd.Amitie.Include(a => a.Receiver).Where(a => a.IdSender == user.Id);
                var q3 = bd.Amitie.Include(a => a.Sender).Where(a => a.IdReceiver == user.Id);

                if (q2 != null || q3 != null)
                {




                    foreach (var item2 in q2)
                    {


                        q.Remove(item2.Receiver);

                    }
                    foreach (var item2 in q3)
                    {
                        q.Remove(item2.Sender);
                    }


                    return View(q);
                }
                else
                {
                    return View(q);
                }


            }


        }
        public async Task<IActionResult> RetirerAmi()
        {
            var type = HttpContext.Session.GetString("UserType");
            if (type is not "membre")
            {
                return RedirectToAction("Login", "Membre");
            }
            else
            {
                var user = GetMembre();
            
                ViewBag.Membre = user.Nom + " " + user.Prenom;

                var q = await bd.Membre.Where(m => m.Id != user.Id).ToListAsync();
                var q2 = bd.Amitie.Include(a => a.Receiver).Where(a => a.IdSender == user.Id && a.Statut == 1);
                var q3 = bd.Amitie.Include(a => a.Sender).Where(a => a.IdReceiver == user.Id && a.Statut==1);

                if (q2 != null || q3 != null)
                {
                    var listAmi = new List<Membre>();

                    foreach (var item2 in q2)
                    {
                        if(!listAmi.Contains(item2.Receiver))
                        {
                            listAmi.Add(item2.Receiver);
                        }

                    }
                    foreach (var item2 in q3)
                    {
                        if (!listAmi.Contains(item2.Sender))
                        {
                            listAmi.Add(item2.Sender);
                        }
                    }
                    ViewBag.checkEnvoi = false;

                    return View(listAmi);
                }
                else
                {
                    ViewBag.checkEnvoi = false;
                    return View();
                }
            }
        }



        [HttpPost, ActionName("RetirerAmi")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ValiderRetrait(int id)
        {
            var type = HttpContext.Session.GetString("UserType");
            if (type is not "membre")
            {
                return RedirectToAction("Login", "Membre");
            }
            else
            {
                var user = GetMembre();
                var amitie = await bd.Amitie.FirstOrDefaultAsync(a=> (a.IdSender==id && a.IdReceiver==user.Id) || (a.IdReceiver == id && a.IdSender == user.Id));
                if(amitie is null)
                {
                    return NotFound();
                }
               
                bd.Amitie.Remove(amitie);
                
                await bd.SaveChangesAsync();

                ViewBag.Membre = user.Nom + " " + user.Prenom;

                var q = await bd.Membre.Where(m => m.Id != user.Id).ToListAsync();
                var q2 = bd.Amitie.Include(a => a.Receiver).Where(a => a.IdSender == user.Id && a.Statut == 1);
                var q3 = bd.Amitie.Include(a => a.Sender).Where(a => a.IdReceiver == user.Id && a.Statut == 1);

                
                    var listAmi = new List<Membre>();

                    foreach (var item2 in q2)
                    {
                        if (!listAmi.Contains(item2.Receiver))
                        {
                            listAmi.Add(item2.Receiver);
                        }

                    }
                    foreach (var item2 in q3)
                    {
                        if (!listAmi.Contains(item2.Sender))
                        {
                            listAmi.Add(item2.Sender);
                        }
                    }
                    ViewBag.checkEnvoi =true;

                    return View(listAmi);
                
            }
        }

        public async Task<IActionResult> MesPub()
        {
            var type = HttpContext.Session.GetString("UserType");
            if (type is not "membre")
            {
                return RedirectToAction("Login", "Membre");
            }
            else
            {

Views/Membre/ListeMembre.cshtml
@model IEnumerable<NetAtlas.Models.Membre>

@{
    ViewData["title"] = "Liste des membres";
    Layout = "_LayoutMembre";
}


<table class="table table-hover">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nom)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Prenom)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Nom)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Prenom)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            
            <td>
                <form asp-action="Create" asp-controller="Amities">
                   <input  type="hidden" value="@item.Id" name="id">
                   <input type="submit" value="Envoyer demande ami">
                </form>
            </td>
        </tr>
}
    </tbody>
</table>

Views/Membre/Login.cshtml
@model NetAtlas.Models.Membre

@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["title"] = "Login";

}


<section>
    <div class="imgbox">
        <img src="~/images/istockphoto-155372496-1024x1024.jpg"/>
    </div>
    <div class="contentBox">
        
        <div class ="formbox">
            <h2>Connectez-vous</h2>
            <form asp-action="Login">
                <div class="inputbox">
                    <span>Email</span>
                    <input asp-for="Email" />
                </div>
                <div class="inputbox">
                    <span>Password</span>
                    <input asp-for="Password" />
                </div>
                <p class="text-danger">@ViewBag.NoneValid</p>
                <div class="inputbox">
                <input type="submit" value="Se connecter" class="btn btn-primary" />
                </div>
            </form>
        </div>
    </div>
</section>
           
			
				
<style>
	*
    {
        margin:0;
        padding:0;
        box-sizing:border-box;
        font-family:'Poppins', sans-serif;
    }	
    section
    {
        position:relative;
        width:100%;
        height:100vh;
        display:flex;
    }
     section .imgbox
    {
        position:relative;
        width:50%;
        height:100%;
    }
    section .imgbox:before
    {
        content:'';
        position:absolute;
        top:0;
        left:0;
        width:100%;
        height:100%;
        background:linear-gradient(skyblue,blue,darkblue);
        z-index:1;
        mix-blend-mode:screen;
    }

   
    section .imgbox img
    {
        position:absolute;
        top:0;
        left:0;
        width:100%;
        height:100%;
        object-fit:cover;

    }
    section .contentBox
    {
        display:flex;
        justify-content: center;
        align-items:center;
        width:50%;
        height:100%;
        right:0;
    }
    section .contentBox .formbox
    {
        width:50%;
    }
    section .contentBox .formbox h2
    {
        color:#607d8b;
        font-weight:600;
        font-size:1.5em;
        text-transform:uppercase;
        margin-bottom:10px;
        border-bottom:4px solid blue;
        display:inline-block;
        letter-spacing:1px;
    }
    section .contentBox .formbox .inputbox
    {
        margin-bottom:5px;
    }
    section .contentBox .formbox .inputbox span
    {
        font-size:16px;
        margin-bottom:5px;
        display:inline-block;
        color:#607d8b;
        font-weight:300;
        letter-spacing:1px;
    }
    section .contentBox .formbox .inputbox input
    {
        width:100%;
        padding:10px 20px;
        outline:none;
        font-weight:400;
        border:1px solid #607d8b;
        font-size:16px;
        letter-spacing:1px;
        color:#607d8b;
        background:transparent;
        border-radius:30px;
    }
    section .contentBox .formbox .inputbox input[type="submit"]
    {
        background:blue;
        color:#fff;
        outline:none;
        border:none;
        font-weight:500;
        cursor-pointer;
    }
    section .contentBox .formbox .inputbox input[type="submit"]:hover
    {
        background:#f53677;
    }
   media(max-width:768px)
    {
        section .imgbox
        {
            position:absolute;
            top:0;
            left:0;
            width:100%;
            height:100%;
        }
        section .contentBox
        {
            display:flex;
            justify-content:center;
            align-items:center;
            width:100%;
            height:100%;
            z-index:1;
        }
        section .contentBox .formbox 
        {
            width:100%;
            padding:40px;
            background:rgb(255 255 255 / 0.9);
            margin:50px;

        }
    }
</style>

Views/Membre/MesPub.cshtml
@model IEnumerable<NetAtlas.Models.Publication>

@{
    Layout = "_LayoutMembre";
}

<div class = "container">
    @if(ViewBag.ListPub is not null)
    {
        @if (ViewBag.check){
            <div class="alert alert-success alert-dismissible col-3" role="alert" style="margin-right:0px;margin-top:0px">
              <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span></button>
              La publication a bien été suprimé
            </div>
        }
        
   
        @foreach (var item in ViewBag.ListPub)
        {
            if(item["ressource"] is Lien)
            {
                <div class="container col-6 bg-light justify-content-center rounded-2 p-3">
                    <small> Lien posté le @item["publication"].DatePublication</small>
                    <h3 class="text-center text-primary">@item["ressource"].nomRessource</h3>
                    <a href="@item["ressource"].Url">@item["ressource"].Url</a>
                    <p>
                    <form asp-action="MesPub" asp-controller="Membre">
                        <input  type="hidden" value="@item["publication"].Id" name="id">
                        <input type="submit" value="Supprimer" class="btn btn-danger" />
                       
                    </form> 
                </p>
                </div>
                <br/>
                
            }
            else if(item["ressource"] is Message)
            {
                <div class="container col-6 bg-light justify-content-center rounded-2 p-3">
                    <small>Message posté le @item["publication"].DatePublication</small>
                   <h3 class="text-center text-primary mt-2">@item["ressource"].nomRessource</h3>
                    <p>@item["ressource"].contenu</p>
                    <p>
                    <form asp-action="MesPub" asp-controller="Membre">
                        <input  type="hidden" value="@item["publication"].Id" name="id">
                        <input type="submit" value="Supprimer" class="btn btn-danger" />
                       
                    </form> 
                </p>
                </div>
                <br/>
            }

            else if(item["ressource"] is PhotoVideo && item["ressource"].TypeMedia==1)
            {
                <div class="container col-6 bg-light justify-content-center rounded-2 p-3">
                    <small>Image posté @item["publication"].DatePublication</small>
                    <h3 class="text-center text-primary mt-2">@item["ressource"].nomRessource</h3>
                    <img class="rounded mx-auto d-block" src='@item["ressource"].Chemin'/>
                    <p>
                        <form asp-action="MesPub" asp-controller="Membre">
                            <input  type="hidden" value="@item["publication"].Id" name="id">
                            <input type="submit" value="Supprimer" class="btn btn-danger" />
                       
                        </form> 
                    </p>
                </div>
                <br/>
            }
            else if(item["ressource"] is PhotoVideo && item["ressource"].TypeMedia==2)
            {
                <div class="container col-6 bg-light justify-content-center p-3">
                    <small>Vidéo posté le @item["publication"].DatePublication</small>
                    <h3 class="text-center bg-primary mt-2">@item["ressource"].nomRessource</h3>
          
                    @*<iframe src='@item["ressource"].Chemin'> </iframe>*@

                    <video width="320" height="240" controls>
                      <source src='@item["ressource"].Chemin' type=video/mp4>
                    </video>
                    <p>
                    <form asp-action="MesPub" asp-controller="Membre">
                        <input  type="hidden" value="@item["publication"].Id" name="id">
                        <input type="submit" value="Supprimer" class="btn btn-danger" />
                       
                    </form> 
                </p>
                </div>
                <br/>
            }
        }
    }
    else
    {
        <h3>Vous n'avez aucune publication. Faite vous des amis pour pouvoir en voir ou creez la votre!</h3>
    }
</div>

Views/Membre/RetirerAmi.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model IEnumerable<NetAtlas.Models.Membre>
@{
    Layout = "_LayoutMembre";
}
@if (ViewBag.checkEnvoi){
            <div class="alert alert-success alert-dismissible col-3" role="alert" style="margin-right:0px;margin-top:0px">
              <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span></button>
              L' email a bien été envoyé
            </div>
        }

<table class="table table-hover">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nom)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Prenom)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Nom)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Prenom)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            
            <td>
                <form asp-action="RetirerAmi" asp-controller="Membre">
                   <input  type="hidden" value="@item.Id" name="id">
                   <input type="submit" value="Retirer">
                </form>
            </td>
        </tr>
}
    </tbody>
</table>